name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:

  achievements:
    runs-on: self-hosted
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: Amateur-God
          base: achievements
          plugin_achievements: yes
          plugin_achievements_threshold: B      # Display achievements with rank B or higher
          plugin_achievements_secrets: yes      # Display unlocked secrets achievements
          plugin_achievements_display: compact  # Use compact display
          plugin_achievements_limit: 0          # Display all unlocked achievements (no limit)

  github-metrics:
    runs-on: self-hosted
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: header.svg
          # You'll need to setup a personal token in your secrets.
          token: ${{ secrets.METRICS_TOKEN }}
          # GITHUB_TOKEN is a special auto-generated token used for commits
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: Amateur-God
          template: classic
          base: header
          config_timezone: ${{ secrets.USER_TIMEZONE }}
  lines:
    runs-on: self-hosted
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: lines-of-code.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "repositories"
          plugin_lines: yes

  acti_comm:
    runs-on: self-hosted
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: acti_comm.svg
          # You'll need to setup a personal token in your secrets.
          token: ${{ secrets.METRICS_TOKEN }}
          # GITHUB_TOKEN is a special auto-generated token used for commits
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: Amateur-God
          template: classic
          base: activity, community
          config_timezone: ${{ secrets.USER_TIMEZONE }}

  iso_calender:
    runs-on: self-hosted
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: iso_calender.svg
          # You'll need to setup a personal token in your secrets.
          token: ${{ secrets.METRICS_TOKEN }}
          # GITHUB_TOKEN is a special auto-generated token used for commits
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: Amateur-God
          template: classic
          base: ""
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: Full-year

  habits:
    runs-on: self-hosted
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: ${{ secrets.USER_TIMEZONE }} # Set timezone
          user: Amateur-God
          base: ""
          template: classic
          plugin_habits: yes
          plugin_habits_from: 200       # Use 200 events to compute habits
          plugin_habits_days: 14        # Keep only events from last 14 days
          plugin_habits_charts: yes     # Display charts section
          plugin_habits_trim: yes       # Trim unused hours on daily chart

  issue_pr_lang:
    runs-on: self-hosted
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: issue_pr_lang.svg
          # You'll need to setup a personal token in your secrets.
          token: ${{ secrets.METRICS_TOKEN }}
          # GITHUB_TOKEN is a special auto-generated token used for commits
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: Amateur-God
          template: classic
          base: ""
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          plugin_followup: yes
          plugin_languages: yes


  repositories:
    runs-on: self-hosted
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: repositories.svg
          # You'll need to setup a personal token in your secrets.
          token: ${{ secrets.METRICS_TOKEN }}
          # GITHUB_TOKEN is a special auto-generated token used for commits
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: Amateur-God
          template: classic
          base: repositories
          config_timezone: ${{ secrets.USER_TIMEZONE }}

  Repositories-diff-history:      
    runs-on: self-hosted
    steps:
    - uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.lines.history.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_lines: yes
        plugin_lines_delay: 30
        plugin_lines_sections: repositories, history
        plugin_lines_repositories_limit: 2
        plugin_lines_history_limit: 1
        repositories_skipped: |
          @use.patterns
          */*
          +lowlighter/metrics

  Comment-reactions:
    runs-on: self-hosted
    steps:
    - uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.reactions.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_reactions: yes
        plugin_reactions_limit: 100
        plugin_reactions_details: percentage
      
  Recent-activity:
    runs-on: self-hosted
    steps:
    - uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.activity.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_activity: yes
        plugin_activity_limit: 5
        plugin_activity_days: 0
        plugin_activity_filter: issue, pr, release, fork, review, ref/create

  snippet:
    runs-on: self-hosted
    steps:
    - uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.code.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_code: yes
        plugin_code_languages: javascript, typescript
        plugin_code_load: 400

  Intro:
    runs-on: self-hosted
    steps:
    - uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.introduction.svg
        token: ${{ secrets.METRICS_TOKEN }}
        user: Amateur-God
        base: header
        plugin_introduction: yes

  Anime:
    runs-on: self-hosted
    steps:
    - uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.anilist.svg
        token: NOT_NEEDED
        base: ""
        plugin_anilist: yes
        plugin_anilist_user: amateurgod
        plugin_anilist_medias: anime
        plugin_anilist_sections: favorites, watching, characters,
        plugin_anilist_limit: 5
        plugin_anilist_limit_characters: 22

  steam:
    runs-on: self-hosted
    steps:
    - uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.steam.full.svg
        token: NOT_NEEDED
        base: ""
        plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
        plugin_steam: yes
        plugin_steam_games_limit: 3
        plugin_steam_playtime_threshold: 3
        plugin_steam_recent_games_limit: 3
        plugin_steam_achievements_limit: 10
        plugin_steam_user: "76561198226668328"
